apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: easyrates-reader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easyrates-reader
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70