---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: socnet
  region: eu-north-1
  version: '1.14'

managedNodeGroups:
  - name: managed-ng
    instanceType: t3.micro
    minSize: 1
    maxSize: 2
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub